### ISSUE TITLE
§1 (1) Name

### ISSUE THREAD

**Issue by PeterTheOne** [CryptoPartyGraz/Statuten#1]
Wie soll der Verein heißen? „`CryptoParty Graz`“? Oder mit einem Zusatz wie zb. der realraum: „`realraum - Verein für Technik in Kultur und Gesellschaft`“ Was könnte ein Zusatz sein? „`CryptoParty Graz – Verein für verschlüsselte Kommunikation und Cybersicherheit`“? :D

Wäre dann im Titel und § 1 (1) zu ergänzen.

**Comment by stefan2904** [comment]
Laut Protokoll von 2015: **Verein zur Förderung der CryptoParty Graz**

**Comment by PeterTheOne** [comment]
> Was spricht gegen "Cryptoparty Graz"?

– Brigitte

**Comment by PeterTheOne** [comment]
Beim Treffen: Cryptoparty Graz oder Verein zur Förderung der CryptoParty Graz

**Comment by flowolf** [comment]
wird vermutlich nicht durchgehen. der Vereinsname muss den Vereinszweck verdeutlichen.

also "CryptoParty Graz - Verein zur Förderung privater Kommunikation in öffentlichen Netzen" oder 
"CryptoParty Graz - Verein für die Erhaltung der Privatsphäre in Zeiten digitaler Kommunikation" oder
"CryptoParty Graz - Verein für die Erhaltung der Privatsphäre in Zeiten digitaler Kommunikation und Datenverarbeitung" oder
"CryptoParty Graz - Verein zur Förderung privater Kommunikation in digitalen Umgebungen" oder
"CryptoParty Graz - Verein zur Erhaltung privater Kommunikation in digitalen Umgebungen" oder
"CryptoParty Graz - Verein zur Erhaltung privater Inhalte in digitalen Umgebungen" oder
"CryptoParty Graz - Verein zur Erhaltung privater Inhalte im digitalen Leben".

**Comment by PeterTheOne** [comment]
> Der Vereinsname muss den Vereinszweck verdeutlichen.

Du hast nicht zufällig eine Quelle dafür herumliegen? Hatten wir nicht schon Gegenbeispiele mit sehr kurzen Namen?

Wie wärs mit: "CryptoParty Graz - Verein zur Förderung privater Kommunikation und Datenverarbeitung"? Wobei sollte auch möglichst mit dem Zweck in den Statuten zusammenpassen:

> Der Verein, dessen Tätigkeit nicht auf Gewinn ausgerichtet ist, fördert einen kreativen und kritischen Umgang mit moderner Informationstechnik, insbesondere mit Fokus auf Datensicherheit und privater Kommunikation im Digitalen.

**Comment by PeterTheOne** [comment]
Inzwischen habe ich mal folgendes reingeschrieben:

> (1) Der Verein führt den Namen „CryptoParty Graz – Verein für Datensicherheit und private Kommunikation im Digitalen“, kurz: „CryptoParty Graz“ oder „CPG“.
