### ISSUE TITLE
§ 6 (2) Austritt, Fristen, etc.

### ISSUE THREAD

**Issue by PeterTheOne** [CryptoPartyGraz/Statuten#11]
> (2) Der Austritt kann nur zum ... erfolgen. Er muss dem Vorstand mindestens ... Monat/e vorher schriftlich mitgeteilt werden. Erfolgt die Anzeige verspätet, so ist sie erst zum nächsten Austrittstermin wirksam. Für die Rechtzeitigkeit ist das Datum der Postaufgabe maßgeblich.

Discuss!

Anmerkung:

> zB 31. Dezember jeden Jahres.

**Comment by PeterTheOne** [comment]
Ich würde das eigentlich flexibel handhaben aber sich auch keine Verpflichtung für zeitnahe Bearbeitung setzen. hmm..

**Comment by stefan2904** [comment]
Jo, falls geht bin ich auch für flexibel. Mitteilen wär halt wohl gut.

Monatsende, paar Wochen vorher, sollt es auch tun.

**Comment by PeterTheOne** [comment]
> Mitteilen wär halt wohl gut.

+1

**Comment by PeterTheOne** [comment]
> Ich finde, der Austritt kann jederzeit erfolgen, aber schriftlich.

– Brigitte

**Comment by PeterTheOne** [comment]
Beim Treffen: schriftlich +1, jederzeit erfolgen. zeitnah behandln.
