### ISSUE TITLE
§ 9 (1) Generalversammlung wie oft?

### ISSUE THREAD

**Issue by PeterTheOne** [CryptoPartyGraz/Statuten#14]
> (1) Die Generalversammlung ist die „Mitgliederversammlung“ im Sinne des Vereinsgesetzes 2002. Eine ordentliche Generalversammlung findet ... statt.

Discuss!

Anmerkung:

> zB jährlich, alle zwei oder alle vier Jahre (abgestimmt auf die Funktionsdauer des Vorstands nach § 11 Abs 3). Das Vereinsgesetz verlangt, dass eine Mitgliederversammlung zumindest alle fünf Jahre einberufen wird.

**Comment by PeterTheOne** [comment]
Vorschlag: 2 Jahre.

**Comment by PeterTheOne** [comment]
Vorstand funktionsperiode § 11  (3) sollte genaus so lang sein.

**Comment by PeterTheOne** [comment]
Auch die Rechnungsprüfer § 14 sollten zumindest bis zur nächsten GV eine funktionsperiode haben.

**Comment by stefan2904** [comment]
:+1: für 1 Jahr 
(warum 2? sind wir schon so stabil?)

**Comment by PeterTheOne** [comment]
1 Jahr wäre auch gut. Man muss dann halt jedes Jahr eine GV machen. Hat aber auch Vorteile wenns kurz ist: Nicht so eine lange Verpflichtung, Last wird aufgeteilt.

**Comment by PeterTheOne** [comment]
Beim Treffen: Alle 2 Jahre, außerordentliche können wir ja dazwischen machen.
