### ISSUE TITLE
§1 (2) Sitz und Tätigkeitsbereich

### ISSUE THREAD

**Issue by PeterTheOne** [CryptoPartyGraz/Statuten#2]
Sitz: `Graz`

> erstreckt seine Tätigkeit auf

Würde ich aus Rechtlichen gründen möglichst nicht weit einschränken. Mein vorschlag: Österreich oder weglassen.

**Comment by PeterTheOne** [comment]
Oder wie 0xFF: 

> Der Verein erstreckt seine Tätigkeiten hauptsächlich auf das Bundesland Steiermark, sowie durch das Internet auf internationales Gebiet.

Wobei mir "internationales Gebiet" nicht so zusagt, vll. nur Internet oder "die Welt".

**Comment by stefan2904** [comment]
Afaik muss man das drin haben, oder? Wir hatten damals gesagt so weit wie möglich, also Österreich? Das Internet wäre natürlich auch toll, wenn das wirklich geht. :-)

**Comment by PeterTheOne** [comment]
Sitz ist wichtig, Tätigkeitsbereich afaik nicht.

**Comment by PeterTheOne** [comment]
> Er hat seinen Sitz in Graz und erstreckt seine Tätigkeit auf ganz Österreich

– Brigitte

**Comment by PeterTheOne** [comment]
Beim Treffen: Sitz Graz, Tätigkeitsbereich International aber hauptsächlich Graz.
