### ISSUE TITLE
LaTeX Vorlage

### ISSUE THREAD

**Issue by flowolf** [CryptoPartyGraz/Statuten#35]
Ich hab vor einiger Zeit für die GLT (www.linuxtage.at) die Statuten in Latex gesetzt. uU könnt Ihr die Bundesvorlage für die CryptoPartyGraz brauchen.

https://github.com/flowolf/AT-Vereinsstatuten

lg

**Comment by PeterTheOne** [comment]
Danke, spätestens beim Druck wird es sinnvoll schauen. Die Änderungen etc. will ich erstmal im Markdown machen..
