### ISSUE TITLE
§ 2: Zweck

### ISSUE THREAD

**Issue by PeterTheOne** [CryptoPartyGraz/Statuten#4]
> Der Verein, dessen Tätigkeit nicht auf Gewinn gerichtet ist, bezweckt ... .

Discuss!

Anmerkung:

> Das Vereinsgesetz verlangt eine klare und umfassende Umschreibung des Zwecks.

**Comment by stefan2904** [comment]
```
Der  Verein,   dessen  Tätigkeit  nicht  auf  Gewinn  ausgerichtet  ist, 
bezweckt   einen   kreativen   und   kritischen   Umgang   mit   moderner   
Informaitonstechnik, insbesondere mit Fokus auf Datensicherheit und 
sicherer Kommunikation im Digitalen.
```

**Comment by PeterTheOne** [comment]
+1

Bezweckt oder vll. doch fördert?

nur sicherere Kommunikation? nicht auch geheime/private?

**Comment by stefan2904** [comment]
(first draft, feel free to change)

**Comment by PeterTheOne** [comment]
Ich hab den draft mal etwas bearbeitet.

**Comment by PeterTheOne** [comment]
Siehe auch: #19 Werte

**Comment by PeterTheOne** [comment]
Beim Treffen:

Text oben ist gut. Wissen vermitteln (oder in den dritten punkt). C3W Statuten sind auch gut. Werte in den Vereinszweck nehmen.
