### ISSUE TITLE
§ 3 (3) materiellen Mittel

### ISSUE THREAD

**Issue by PeterTheOne** [CryptoPartyGraz/Statuten#6]
> (1) Der Vereinszweck soll durch die in den Abs. 2 und 3 angeführten ideellen und materiellen Mittel erreicht werden.
> (3) Die erforderlichen materiellen Mittel sollen aufgebracht werden durch a) Beitrittsgebühren und Mitgliedsbeiträge b) ... c) ... d) ... e) ...

Discuss!

Anmerkung:

> "Für ein auf die Erlangung steuerlicher Begünstigungen bei Betätigung für gemeinnützige, mildtätige oder kirchliche Zwecke (§§ 34 ff BAO) abgestimmtes Statutenmuster siehe unter Vereinsrichtlinien des Bundesministeriums für Finanzen. Sie finden das Muster dort unter Punkt 13."

> Abgesehen von den weithin üblichen Beitrittsgebühren und Mitgliedsbeiträgen kommen zB Erträgnisse aus Veranstaltungen oder aus vereinseigenen Unternehmungen, Spenden, Sammlungen, Vermächtnisse und sonstige Zuwendungen in Betracht.

**Comment by PeterTheOne** [comment]
Ich würde ja Beitrittsgebühren rausnehmen, siehe #7.

Sonst dazu nehmen:
- Spenden
- Förderungen
- Erträge aus Vorträgen, Workshops oder sonstigen Dienstleistungen des Vereins

**Comment by stefan2904** [comment]
:+1: 

wobei, wollen wir Mitgliedsbeiträge? Symbolische oder garkeine?

**Comment by PeterTheOne** [comment]
Würde ich uns von den Statuten her eigentlich offen lassen. Die GV kann ja die höhe auf 0 setzen.

**Comment by PeterTheOne** [comment]
> a) Beitrittsgebühren und Mitgliedsbeiträge
b) Kostenentschädigung für Vorträge und Workshops
c) öffentliche Förderung (vielleicht wollen wir einmal bei irgendeinem Projekt mitmachen, was da steht müssen wir nicht tun, aber wenn nix da steht, können wir es nicht tun)

– Brigitte

**Comment by PeterTheOne** [comment]
Beim Treffen: Erträge aus Veranstaltungen, Publikationen, Sponsorbeiträge.
