### ISSUE TITLE
§ 5 (1) Erwerb der Mitgliedschaft, wer?

### ISSUE THREAD

**Issue by PeterTheOne** [CryptoPartyGraz/Statuten#9]
> Mitglieder des Vereins können alle physischen Personen, die ... , sowie juristische Personen und rechtsfähige Personengesellschaften werden.

Discuss!

Anmerkung:

> Beschränkungen zB hinsichtlich des Alters, des Geschlechtes, der Staatsbürgerschaft, des Berufes, der Unbescholtenheit sind möglich, aber nicht geboten.

**Comment by PeterTheOne** [comment]
Ich schlage vor #10.

**Comment by stefan2904** [comment]
"alle Personen, keine juristischen" klingt gut. Evtl noch darauf beschränken, den "Werten" der CryptoParty zuzustimmen?

Wo kommt rein wer Mitglieder annehmen darf?

**Comment by PeterTheOne** [comment]
> Evtl noch darauf beschränken, den "Werten" der CryptoParty zuzustimmen?

+1

> Wo kommt rein wer Mitglieder annehmen darf?

#12

**Comment by PeterTheOne** [comment]
Werte: #19

**Comment by PeterTheOne** [comment]
> Mitglieder des Vereins können alle physischen Personen, **die die Vereinsziele unterstützen**, [...]

– Brigitte

**Comment by PeterTheOne** [comment]
Beim Treffen: +1 zu "die die Vereinsziele unterstützen"
